[build]
functions = "netlify/functions"

[[headers]]
  for = "/.netlify/images/*"  # Match your image paths here
  [headers.values]
    Access-Control-Allow-Origin = "https://i.imgur.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/.netlify/images/*"  # Match your image paths here
  [headers.values]
    Access-Control-Allow-Origin = "https://res.cloudinary.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

