[build]
functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/images/*"
  to = "/.netlify/images/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://i.imgur.com" 
  }

[[redirects]]
  from = "/.netlify/images/*"
  to = "/.netlify/images/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "https://res.cloudinary.com" 
  }

